# -*- coding: utf-8 -*-
{
    'name': "Wagon Inventory",
    'category': 'Sales',
    'version': '14.0.9.3.7',
    'author': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': [
        'base',
        'hr',
        'sale_management',
        'stock',
        'purchase',
        'stock_barcode_picking_batch',
        'woo_commerce_connector',
        'wagon_basket_delivery'
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/purchase_order.xml',
        'views/stock_move.xml',
        'views/trolley.xml',
        'views/product_template.xml',
        'views/package.xml',
        'data/sequence.xml',
        'views/trolley_location.xml',
        'views/stock_picking_batch.xml',
        'views/stock_picking_type.xml',
        'report/paperformat.xml',
        'report/trolley_barcode.xml',
        'report/crate_barcode.xml',
        'report/ crate_barcode_template.xml',
        'report/trolley_template.xml',
        'views/assets.xml',
        'views/food_vegetables.xml',
        'views/action_manager.xml',
    ],
    'qweb': ['static/src/xml/barcode_template.xml',],
    'installable': True,
    'application': True,
    'auto_install': False,
}
